# Generated by Django 3.0.8 on 2020-07-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0002_auto_20200708_1715'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='users.Role'),
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userorganization', to='orders_api.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userorganization', to='users.Role')),
            ],
        ),
    ]
