# Generated by Django 3.0.8 on 2020-07-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='paymentmethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders_api.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='shippingmethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders_api.ShippingMethod'),
        ),
    ]
