# Generated by Django 3.0.8 on 2020-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0003_auto_20200713_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
