# Generated by Django 3.0.8 on 2020-07-13 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders_api', '0007_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/img/uploads/logo/'),
            preserve_default=False,
        ),
    ]
